[package]
name = "sparkfun-otos"
version = "0.1.0"
edition = "2024"

[dependencies]
maybe-async = "0.2.11"
embedded-hal-async = { optional = true, version = "1.0.0" }
embedded-hal = { optional = true, version = "1.0.0" }


[features]
default = ["dep:embedded-hal-async"]
blocking = ["dep:embedded-hal", "maybe-async/is_sync"]
